// <auto-generated />
using System;
using System.Collections.Generic;
using ElBaul.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElBaul.Infra.Migrations
{
    [DbContext(typeof(ElBaulDbContext))]
    [Migration("20260819062424_RequirePhotoDimensions")]
    partial class RequirePhotoDimensions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElBaul.Core.Bauls.Domain.Baul", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CoverPhotoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustodioId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CoverCrop", "ElBaul.Core.Bauls.Domain.Baul.CoverCrop#ImageCrop", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Scale")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(4, 2)
                                .HasColumnType("numeric(4,2)")
                                .HasDefaultValue(1m)
                                .HasColumnName("CoverCropScale");

                            b1.Property<decimal>("X")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.5m)
                                .HasColumnName("CoverCropX");

                            b1.Property<decimal>("Y")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.5m)
                                .HasColumnName("CoverCropY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CoverPhotoId");

                    b.HasIndex("CustodioId");

                    b.ToTable("Baules", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Chapters.Domain.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverPhotoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CoverCrop", "ElBaul.Core.Chapters.Domain.Chapter.CoverCrop#ImageCrop", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Scale")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(4, 2)
                                .HasColumnType("numeric(4,2)")
                                .HasDefaultValue(1m)
                                .HasColumnName("CoverCropScale");

                            b1.Property<decimal>("X")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.5m)
                                .HasColumnName("CoverCropX");

                            b1.Property<decimal>("Y")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.5m)
                                .HasColumnName("CoverCropY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BaulId");

                    b.HasIndex("CoverPhotoId");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Chat.Domain.ChatMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BaulId", "UserId");

                    b.ToTable("ChatMemories", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Chat.Domain.ChatMemoryEmbedding", b =>
                {
                    b.Property<Guid>("ChatMemoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.PrimitiveCollection<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.HasKey("ChatMemoryId");

                    b.HasIndex("BaulId", "UserId");

                    b.ToTable("ChatMemoryEmbeddings", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Chat.Domain.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BaulId", "UserId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Feed.Domain.BaulFeedCursor", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BaulId");

                    b.HasIndex("BaulId");

                    b.ToTable("BaulFeedCursors", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Moderation.Domain.RemovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoStorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BaulId");

                    b.ToTable("RemovalRequests", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Notifications.Domain.EmailLinkClick", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FirstClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SentEmailId")
                        .HasColumnType("uuid");

                    b.HasKey("Token");

                    b.HasIndex("SentEmailId");

                    b.ToTable("EmailLinkClicks", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Notifications.Domain.PushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushTokens", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Notifications.Domain.SentEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivitySince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActivityUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("SendAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("SentEmails", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Personas.Domain.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvatarPhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<string>("Biografia")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("InvitedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AvatarCrop", "ElBaul.Core.Personas.Domain.Persona.AvatarCrop#ImageCrop", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Scale")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(4, 2)
                                .HasColumnType("numeric(4,2)")
                                .HasDefaultValue(1m)
                                .HasColumnName("AvatarCropScale");

                            b1.Property<decimal>("X")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.5m)
                                .HasColumnName("AvatarCropX");

                            b1.Property<decimal>("Y")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.5m)
                                .HasColumnName("AvatarCropY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AvatarPhotoId");

                    b.HasIndex("BaulId");

                    b.HasIndex("UserId");

                    b.HasIndex("BaulId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Personas.Domain.PhotoPersonaTag", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PhotoId", "PersonaId");

                    b.HasIndex("BaulId");

                    b.HasIndex("PersonaId");

                    b.ToTable("PhotoPersonaTags", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Photos.Domain.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientUploadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConfirmedNoPersonas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OriginalContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("OriginalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("SizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UploadBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dimensions", "ElBaul.Core.Photos.Domain.Photo.Dimensions#ImageDimensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("Height");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("Width");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OriginalDimensions", "ElBaul.Core.Photos.Domain.Photo.OriginalDimensions#ImageDimensions", b1 =>
                        {
                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("OriginalHeight");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("OriginalWidth");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TakenAt", "ElBaul.Core.Photos.Domain.Photo.TakenAt#PhotoDate", b1 =>
                        {
                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("DateDay");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("DateMonth");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("DateYear");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BaulId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ClientUploadId")
                        .IsUnique();

                    b.HasIndex("UploadBatchId");

                    b.HasIndex("BaulId", "OriginalContentHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Photos_BaulId_OriginalContentHash_Active")
                        .HasFilter("\"Status\" = 'Active' AND \"OriginalContentHash\" IS NOT NULL");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Recuerdos.Domain.Recuerdo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BaulId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Recuerdos", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Recuerdos.Domain.RecuerdoEmbedding", b =>
                {
                    b.Property<Guid>("RecuerdoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.HasKey("RecuerdoId");

                    b.HasIndex("BaulId");

                    b.ToTable("RecuerdoEmbeddings", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Sharing.Domain.BaulInviteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("BaulId")
                        .IsUnique()
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("BaulInviteLinks", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Sharing.Domain.SharedLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecuerdoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("BaulId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PhotoId");

                    b.HasIndex("RecuerdoId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("SharedLinks", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.TvMode.Domain.TvPairing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimedSessionToken")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TvPairings", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.TvMode.Domain.TvSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaulId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("BaulId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("TvSessions", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Users.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("HasSeenOnboarding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPushDigestSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WeeklyDigestEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ElBaul.Core.Bauls.Domain.Baul", b =>
                {
                    b.HasOne("ElBaul.Core.Photos.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("CoverPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CustodioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Chapters.Domain.Chapter", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Photos.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("CoverPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ElBaul.Core.Chat.Domain.ChatMemory", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Chat.Domain.ChatMemoryEmbedding", b =>
                {
                    b.HasOne("ElBaul.Core.Chat.Domain.ChatMemory", null)
                        .WithOne()
                        .HasForeignKey("ElBaul.Core.Chat.Domain.ChatMemoryEmbedding", "ChatMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Chat.Domain.ChatMessage", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Feed.Domain.BaulFeedCursor", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Moderation.Domain.RemovalRequest", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Notifications.Domain.EmailLinkClick", b =>
                {
                    b.HasOne("ElBaul.Core.Notifications.Domain.SentEmail", null)
                        .WithMany()
                        .HasForeignKey("SentEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Notifications.Domain.PushToken", b =>
                {
                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Notifications.Domain.SentEmail", b =>
                {
                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Personas.Domain.Persona", b =>
                {
                    b.HasOne("ElBaul.Core.Photos.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("AvatarPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ElBaul.Core.Personas.Domain.PhotoPersonaTag", b =>
                {
                    b.HasOne("ElBaul.Core.Personas.Domain.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Photos.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Photos.Domain.Photo", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Chapters.Domain.Chapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ElBaul.Core.Recuerdos.Domain.Recuerdo", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Chapters.Domain.Chapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElBaul.Core.Photos.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Recuerdos.Domain.RecuerdoEmbedding", b =>
                {
                    b.HasOne("ElBaul.Core.Recuerdos.Domain.Recuerdo", null)
                        .WithOne()
                        .HasForeignKey("ElBaul.Core.Recuerdos.Domain.RecuerdoEmbedding", "RecuerdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Sharing.Domain.BaulInviteLink", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElBaul.Core.Sharing.Domain.SharedLink", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Photos.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElBaul.Core.Recuerdos.Domain.Recuerdo", null)
                        .WithMany()
                        .HasForeignKey("RecuerdoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ElBaul.Core.TvMode.Domain.TvSession", b =>
                {
                    b.HasOne("ElBaul.Core.Bauls.Domain.Baul", null)
                        .WithMany()
                        .HasForeignKey("BaulId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElBaul.Core.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
