// <auto-generated />
using ElBaul.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ElBaul.Infra.Migrations
{
    [DbContext(typeof(ElBaulDbContext))]
    [Migration("20260728120000_AddSharedLinks")]
    partial class AddSharedLinks
    {
    }
}
