name: Imgproxy CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/imgproxy-deploy.yml'
      - 'imgproxy/**'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}-imgproxy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package imgproxy image
        uses: ./.github/actions/docker-build-image
        with:
          image: ${{ env.IMAGE_NAME }}:latest
          context: imgproxy

      - name: Release imgproxy image
        uses: ./.github/actions/release-ghcr-image
        with:
          image: ${{ env.IMAGE_NAME }}:latest
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy imgproxy
        uses: ./.github/actions/deploy-coolify
        with:
          webhook: ${{ secrets.COOLIFY_WEBHOOK_IMGPROXY }}
          token: ${{ secrets.COOLIFY_API_TOKEN }}
